# Generated by Django 4.2.7 on 2023-12-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_subscribe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_img',
            field=models.ImageField(blank=True, default='static/images/image.png', upload_to='userimages/'),
        ),
    ]
