# Generated by Django 4.2.7 on 2023-12-24 06:18

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_userdetails_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='Asia/Kolkata'),
        ),
        migrations.AddField(
            model_name='comments',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='Asia/Kolkata'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='Asia/Kolkata'),
        ),
    ]
