# Generated by Django 4.2.7 on 2023-12-27 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0013_alter_blogpost_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='like',
            field=models.ManyToManyField(related_name='postlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
