# Generated by Django 4.2.7 on 2023-12-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('company', models.CharField(max_length=100)),
                ('posted_on', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='applyjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('pg', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(max_length=100)),
                ('PU', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('resume', models.ImageField(blank=True, upload_to='resume/')),
                ('jobtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpostdata.jobdata')),
            ],
        ),
    ]
