# Generated by Django 4.2.7 on 2023-12-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_comment_reply_delete_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='parent',
        ),
    ]
