# Generated by Django 4.2.7 on 2023-12-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_blogpost_time_zone_comments_time_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
