# Generated by Django 4.2.7 on 2024-01-02 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0014_blogpost_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
